/*
 * ═══════════════════════════════════════════════════════════════════════════
 * 이 파일은 **생성물이다. 손으로 고치지 마세요.**
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * 출처(단일 진실):
 *   supabase/migrations/20260817094100_seed_boss_master.sql        (보스·난이도·가격·별칭)
 *   supabase/migrations/20260818120000_party_bosses_and_short_names.sql (줄임말·별칭 9)
 *
 * 다시 만들기:  pnpm boss-master
 * 어긋남 검사:  pnpm boss-master:check   ← `pnpm build` 가 자동으로 먼저 돌린다
 *
 * 왜 코드 상수인가 (발주자 지시, 2026-08-18):
 *   *"보스같은건 그냥 고정값으로 박아버리던가. 개발에서 명시적으로 패치해야지 db에서
 *     한번 가져와서 쭉 고정해서 값으로 가지고있는게 나을듯. 가격도 포함."*
 *   보스 마스터는 게임 패치 때만 바뀌는데도 탭을 옮길 때마다 왕복 하나를 먹고 있었다.
 *   왕복 하나당 고정비가 300ms 수준이라(실측 `/api/auth/me` 0.30s) 지우는 편이 낫다.
 *
 * ⚠️ DB 표는 그대로 남는다. `character_boss_plans` · `party_runs` · `party_bosses` ·
 *    `boss_clears` 가 전부 `boss_difficulty_id` 를 FK 로 참조하므로 참조 무결성은
 *    여전히 DB 가 갖는다. 바뀐 것은 **읽는 경로**뿐이다 — 표시·검색·가격은 이 상수에서.
 */

import type { BossCycle, BossDifficultyTier } from "@/types/domain";

/** ← `public.bosses` 한 행. */
export interface GeneratedBossGroup {
  readonly id: string;
  /** 난이도가 붙지 않은 이름. 예: `스우` */
  readonly koreanName: string;
  readonly generation: string;
  /** 넥슨 스케줄러 API 의 `content_name`. 매핑 조인 키다. */
  readonly nexonContentName: string;
  readonly nexonNameVerified: boolean;
  readonly sortOrder: number;
}

/** ← `public.boss_difficulties` 한 행. */
export interface GeneratedBossDifficulty {
  readonly id: string;
  readonly bossId: string;
  /** 난이도가 이미 붙은 이름. 예: `하드 스우` */
  readonly koreanName: string;
  readonly difficulty: BossDifficultyTier;
  readonly cycle: BossCycle;
  /** **소프트 상한**이다 (§1.3 D5). 초과를 막지 않고 경고만 한다. */
  readonly maxParty: number;
  readonly entryLevel: number;
  readonly released: boolean;
  readonly nexonDifficulty: string | null;
  readonly sortOrder: number;
  /** 좁은 자리 전용 줄임말. 예: `하스`. 없으면 null. */
  readonly shortName: string | null;
  /**
   * 주간 결정석 **12칸을 소비하는가**. 거의 언제나 `true` 다.
   *
   * `false` 는 주간(weekly) 보스이면서도 12칸에 들어가지 않는 시즌/이벤트 보스뿐이다
   * (메이린). 이 구분이 없으면 그 보스 하나 때문에 체크리스트가 `13/12` 를 띄우고,
   * 밤 동기화가 그 캐릭터를 "다 찼다"로 보고 건너뛴다.
   */
  readonly countsTowardWeeklyLimit: boolean;
}

/** ← `public.boss_crystal_prices` 한 행. 효력 시작 시각을 갖는 이력 행이다. */
export interface GeneratedBossPrice {
  readonly bossDifficultyId: string;
  /** `null` = **미확인**(§1.3 D4). 0 이 아니며 합계에서 제외된다. */
  readonly priceMeso: number | null;
  /** ISO 순간(UTC). 원본은 `timestamptz ... +09` 다. */
  readonly effectiveFrom: string;
  readonly patchLabel: string;
}

/** ← `public.boss_aliases` 한 행. `bossDifficultyId` 가 null 이면 보스 전체 별칭. */
export interface GeneratedBossAlias {
  readonly bossId: string;
  readonly bossDifficultyId: string | null;
  readonly alias: string;
  /** `lower(btrim(replace(alias, " ", "")))` — DB CHECK 와 같은 정규화. */
  readonly normalizedAlias: string;
}

/** 33건. */
export const GENERATED_BOSS_GROUPS: readonly GeneratedBossGroup[] = [
  { id: "zakum", koreanName: "자쿰", generation: "classic", nexonContentName: "자쿰", nexonNameVerified: true, sortOrder: 10 },
  { id: "papulatus", koreanName: "파풀라투스", generation: "classic", nexonContentName: "파풀라투스", nexonNameVerified: true, sortOrder: 20 },
  { id: "magnus", koreanName: "매그너스", generation: "classic", nexonContentName: "매그너스", nexonNameVerified: true, sortOrder: 30 },
  { id: "hilla", koreanName: "힐라", generation: "classic", nexonContentName: "힐라", nexonNameVerified: true, sortOrder: 40 },
  { id: "horntail", koreanName: "혼테일", generation: "classic", nexonContentName: "혼테일", nexonNameVerified: true, sortOrder: 50 },
  { id: "bloody_queen", koreanName: "블러디퀸", generation: "classic", nexonContentName: "블러디퀸", nexonNameVerified: true, sortOrder: 60 },
  { id: "von_bon", koreanName: "반반", generation: "classic", nexonContentName: "반반", nexonNameVerified: true, sortOrder: 70 },
  { id: "pierre", koreanName: "피에르", generation: "classic", nexonContentName: "피에르", nexonNameVerified: true, sortOrder: 80 },
  { id: "vellum", koreanName: "벨룸", generation: "classic", nexonContentName: "벨룸", nexonNameVerified: true, sortOrder: 90 },
  { id: "von_leon", koreanName: "반 레온", generation: "classic", nexonContentName: "반 레온", nexonNameVerified: true, sortOrder: 100 },
  { id: "arkarium", koreanName: "아카이럼", generation: "classic", nexonContentName: "아카이럼", nexonNameVerified: true, sortOrder: 110 },
  { id: "kaung", koreanName: "카웅", generation: "classic", nexonContentName: "카웅", nexonNameVerified: true, sortOrder: 120 },
  { id: "pink_bean", koreanName: "핑크빈", generation: "classic", nexonContentName: "핑크빈", nexonNameVerified: true, sortOrder: 130 },
  { id: "cygnus", koreanName: "시그너스", generation: "classic", nexonContentName: "시그너스", nexonNameVerified: true, sortOrder: 140 },
  { id: "lotus", koreanName: "스우", generation: "classic", nexonContentName: "스우", nexonNameVerified: true, sortOrder: 150 },
  { id: "damien", koreanName: "데미안", generation: "classic", nexonContentName: "데미안", nexonNameVerified: true, sortOrder: 160 },
  { id: "guardian_angel_slime", koreanName: "가디언 엔젤 슬라임", generation: "classic", nexonContentName: "가디언 엔젤 슬라임", nexonNameVerified: true, sortOrder: 170 },
  { id: "lucid", koreanName: "루시드", generation: "classic", nexonContentName: "루시드", nexonNameVerified: true, sortOrder: 180 },
  { id: "will", koreanName: "윌", generation: "classic", nexonContentName: "윌", nexonNameVerified: true, sortOrder: 190 },
  { id: "dusk", koreanName: "더스크", generation: "classic", nexonContentName: "더스크", nexonNameVerified: true, sortOrder: 200 },
  { id: "dunkel", koreanName: "듄켈", generation: "classic", nexonContentName: "듄켈", nexonNameVerified: true, sortOrder: 210 },
  { id: "verus_hilla", koreanName: "진 힐라", generation: "classic", nexonContentName: "진 힐라", nexonNameVerified: true, sortOrder: 220 },
  { id: "seren", koreanName: "선택받은 세렌", generation: "classic", nexonContentName: "선택받은 세렌", nexonNameVerified: true, sortOrder: 230 },
  { id: "kalos", koreanName: "감시자 칼로스", generation: "classic", nexonContentName: "감시자 칼로스", nexonNameVerified: true, sortOrder: 240 },
  { id: "first_adversary", koreanName: "최초의 대적자", generation: "modern", nexonContentName: "최초의 대적자", nexonNameVerified: true, sortOrder: 250 },
  { id: "kaling", koreanName: "카링", generation: "classic", nexonContentName: "카링", nexonNameVerified: true, sortOrder: 260 },
  { id: "bellona", koreanName: "벨로나", generation: "modern", nexonContentName: "벨로나", nexonNameVerified: false, sortOrder: 270 },
  { id: "radiant_malefic_star", koreanName: "찬란한 흉성", generation: "modern", nexonContentName: "찬란한 흉성", nexonNameVerified: true, sortOrder: 280 },
  { id: "limbo", koreanName: "림보", generation: "modern", nexonContentName: "림보", nexonNameVerified: true, sortOrder: 290 },
  { id: "baldrix", koreanName: "발드릭스", generation: "modern", nexonContentName: "발드릭스", nexonNameVerified: true, sortOrder: 300 },
  { id: "jupiter", koreanName: "유피테르", generation: "modern", nexonContentName: "유피테르", nexonNameVerified: true, sortOrder: 310 },
  { id: "black_mage", koreanName: "검은 마법사", generation: "classic", nexonContentName: "검은 마법사", nexonNameVerified: true, sortOrder: 320 },
  { id: "meilin", koreanName: "메이린", generation: "modern", nexonContentName: "시즌 보스 메이린", nexonNameVerified: true, sortOrder: 900 },
];

/** 80건 (일간 24 · 주간 54 · 월간 2). */
export const GENERATED_BOSS_DIFFICULTIES: readonly GeneratedBossDifficulty[] = [
  { id: "zakum_easy", bossId: "zakum", koreanName: "이지 자쿰", difficulty: "easy", cycle: "daily", maxParty: 6, entryLevel: 50, released: true, nexonDifficulty: "easy", sortOrder: 10, shortName: "이자", countsTowardWeeklyLimit: true },
  { id: "zakum_normal", bossId: "zakum", koreanName: "노멀 자쿰", difficulty: "normal", cycle: "daily", maxParty: 6, entryLevel: 90, released: true, nexonDifficulty: "normal", sortOrder: 20, shortName: "노자", countsTowardWeeklyLimit: true },
  { id: "papulatus_easy", bossId: "papulatus", koreanName: "이지 파풀라투스", difficulty: "easy", cycle: "daily", maxParty: 6, entryLevel: 115, released: true, nexonDifficulty: "easy", sortOrder: 30, shortName: "이파", countsTowardWeeklyLimit: true },
  { id: "magnus_easy", bossId: "magnus", koreanName: "이지 매그너스", difficulty: "easy", cycle: "daily", maxParty: 6, entryLevel: 115, released: true, nexonDifficulty: "easy", sortOrder: 40, shortName: "이매", countsTowardWeeklyLimit: true },
  { id: "hilla_normal", bossId: "hilla", koreanName: "노멀 힐라", difficulty: "normal", cycle: "daily", maxParty: 6, entryLevel: 85, released: true, nexonDifficulty: "normal", sortOrder: 50, shortName: "노힐", countsTowardWeeklyLimit: true },
  { id: "horntail_easy", bossId: "horntail", koreanName: "이지 혼테일", difficulty: "easy", cycle: "daily", maxParty: 6, entryLevel: 130, released: true, nexonDifficulty: "easy", sortOrder: 60, shortName: "이혼", countsTowardWeeklyLimit: true },
  { id: "bloody_queen_normal", bossId: "bloody_queen", koreanName: "노멀 블러디퀸", difficulty: "normal", cycle: "daily", maxParty: 6, entryLevel: 125, released: true, nexonDifficulty: "normal", sortOrder: 70, shortName: "노블", countsTowardWeeklyLimit: true },
  { id: "von_bon_normal", bossId: "von_bon", koreanName: "노멀 반반", difficulty: "normal", cycle: "daily", maxParty: 6, entryLevel: 125, released: true, nexonDifficulty: "normal", sortOrder: 80, shortName: "노반", countsTowardWeeklyLimit: true },
  { id: "pierre_normal", bossId: "pierre", koreanName: "노멀 피에르", difficulty: "normal", cycle: "daily", maxParty: 6, entryLevel: 125, released: true, nexonDifficulty: "normal", sortOrder: 90, shortName: "노피", countsTowardWeeklyLimit: true },
  { id: "vellum_normal", bossId: "vellum", koreanName: "노멀 벨룸", difficulty: "normal", cycle: "daily", maxParty: 6, entryLevel: 125, released: true, nexonDifficulty: "normal", sortOrder: 100, shortName: null, countsTowardWeeklyLimit: true },
  { id: "horntail_normal", bossId: "horntail", koreanName: "노멀 혼테일", difficulty: "normal", cycle: "daily", maxParty: 6, entryLevel: 130, released: true, nexonDifficulty: "normal", sortOrder: 110, shortName: "노혼", countsTowardWeeklyLimit: true },
  { id: "von_leon_easy", bossId: "von_leon", koreanName: "이지 반 레온", difficulty: "easy", cycle: "daily", maxParty: 6, entryLevel: 125, released: true, nexonDifficulty: "easy", sortOrder: 120, shortName: "이레", countsTowardWeeklyLimit: true },
  { id: "arkarium_easy", bossId: "arkarium", koreanName: "이지 아카이럼", difficulty: "easy", cycle: "daily", maxParty: 6, entryLevel: 140, released: true, nexonDifficulty: "easy", sortOrder: 130, shortName: "이아", countsTowardWeeklyLimit: true },
  { id: "kaung_normal", bossId: "kaung", koreanName: "노멀 카웅", difficulty: "normal", cycle: "daily", maxParty: 6, entryLevel: 180, released: true, nexonDifficulty: "normal", sortOrder: 140, shortName: "노웅", countsTowardWeeklyLimit: true },
  { id: "horntail_chaos", bossId: "horntail", koreanName: "카오스 혼테일", difficulty: "chaos", cycle: "daily", maxParty: 6, entryLevel: 135, released: true, nexonDifficulty: "chaos", sortOrder: 150, shortName: "카혼", countsTowardWeeklyLimit: true },
  { id: "pink_bean_normal", bossId: "pink_bean", koreanName: "노멀 핑크빈", difficulty: "normal", cycle: "daily", maxParty: 6, entryLevel: 140, released: true, nexonDifficulty: "normal", sortOrder: 160, shortName: "노핑", countsTowardWeeklyLimit: true },
  { id: "von_leon_normal", bossId: "von_leon", koreanName: "노멀 반 레온", difficulty: "normal", cycle: "daily", maxParty: 6, entryLevel: 125, released: true, nexonDifficulty: "normal", sortOrder: 170, shortName: "노레", countsTowardWeeklyLimit: true },
  { id: "von_leon_hard", bossId: "von_leon", koreanName: "하드 반 레온", difficulty: "hard", cycle: "daily", maxParty: 6, entryLevel: 125, released: true, nexonDifficulty: "hard", sortOrder: 180, shortName: "하레", countsTowardWeeklyLimit: true },
  { id: "arkarium_normal", bossId: "arkarium", koreanName: "노멀 아카이럼", difficulty: "normal", cycle: "daily", maxParty: 6, entryLevel: 140, released: true, nexonDifficulty: "normal", sortOrder: 190, shortName: "노아", countsTowardWeeklyLimit: true },
  { id: "magnus_normal", bossId: "magnus", koreanName: "노멀 매그너스", difficulty: "normal", cycle: "daily", maxParty: 6, entryLevel: 155, released: true, nexonDifficulty: "normal", sortOrder: 200, shortName: "노매", countsTowardWeeklyLimit: true },
  { id: "papulatus_normal", bossId: "papulatus", koreanName: "노멀 파풀라투스", difficulty: "normal", cycle: "daily", maxParty: 6, entryLevel: 155, released: true, nexonDifficulty: "normal", sortOrder: 210, shortName: "노파", countsTowardWeeklyLimit: true },
  { id: "hilla_hard", bossId: "hilla", koreanName: "하드 힐라", difficulty: "hard", cycle: "daily", maxParty: 6, entryLevel: 170, released: true, nexonDifficulty: "hard", sortOrder: 220, shortName: "하힐", countsTowardWeeklyLimit: true },
  { id: "pink_bean_chaos", bossId: "pink_bean", koreanName: "카오스 핑크빈", difficulty: "chaos", cycle: "daily", maxParty: 6, entryLevel: 170, released: true, nexonDifficulty: "chaos", sortOrder: 230, shortName: "카핑", countsTowardWeeklyLimit: true },
  { id: "cygnus_normal", bossId: "cygnus", koreanName: "노멀 시그너스", difficulty: "normal", cycle: "daily", maxParty: 6, entryLevel: 165, released: true, nexonDifficulty: "normal", sortOrder: 240, shortName: "노시", countsTowardWeeklyLimit: true },
  { id: "zakum_chaos", bossId: "zakum", koreanName: "카오스 자쿰", difficulty: "chaos", cycle: "weekly", maxParty: 6, entryLevel: 90, released: true, nexonDifficulty: "chaos", sortOrder: 310, shortName: "카자", countsTowardWeeklyLimit: true },
  { id: "bloody_queen_chaos", bossId: "bloody_queen", koreanName: "카오스 블러디퀸", difficulty: "chaos", cycle: "weekly", maxParty: 6, entryLevel: 180, released: true, nexonDifficulty: "chaos", sortOrder: 320, shortName: "카블", countsTowardWeeklyLimit: true },
  { id: "von_bon_chaos", bossId: "von_bon", koreanName: "카오스 반반", difficulty: "chaos", cycle: "weekly", maxParty: 6, entryLevel: 180, released: true, nexonDifficulty: "chaos", sortOrder: 330, shortName: "카반", countsTowardWeeklyLimit: true },
  { id: "pierre_chaos", bossId: "pierre", koreanName: "카오스 피에르", difficulty: "chaos", cycle: "weekly", maxParty: 6, entryLevel: 180, released: true, nexonDifficulty: "chaos", sortOrder: 340, shortName: "카피", countsTowardWeeklyLimit: true },
  { id: "magnus_hard", bossId: "magnus", koreanName: "하드 매그너스", difficulty: "hard", cycle: "weekly", maxParty: 6, entryLevel: 175, released: true, nexonDifficulty: "hard", sortOrder: 350, shortName: "하매", countsTowardWeeklyLimit: true },
  { id: "vellum_chaos", bossId: "vellum", koreanName: "카오스 벨룸", difficulty: "chaos", cycle: "weekly", maxParty: 6, entryLevel: 180, released: true, nexonDifficulty: "chaos", sortOrder: 360, shortName: null, countsTowardWeeklyLimit: true },
  { id: "papulatus_chaos", bossId: "papulatus", koreanName: "카오스 파풀라투스", difficulty: "chaos", cycle: "weekly", maxParty: 6, entryLevel: 190, released: true, nexonDifficulty: "chaos", sortOrder: 370, shortName: "카파", countsTowardWeeklyLimit: true },
  { id: "lotus_normal", bossId: "lotus", koreanName: "노멀 스우", difficulty: "normal", cycle: "weekly", maxParty: 6, entryLevel: 190, released: true, nexonDifficulty: "normal", sortOrder: 380, shortName: "노스", countsTowardWeeklyLimit: true },
  { id: "damien_normal", bossId: "damien", koreanName: "노멀 데미안", difficulty: "normal", cycle: "weekly", maxParty: 6, entryLevel: 190, released: true, nexonDifficulty: "normal", sortOrder: 390, shortName: "노데", countsTowardWeeklyLimit: true },
  { id: "guardian_angel_slime_normal", bossId: "guardian_angel_slime", koreanName: "노멀 가디언 엔젤 슬라임", difficulty: "normal", cycle: "weekly", maxParty: 6, entryLevel: 210, released: true, nexonDifficulty: "normal", sortOrder: 400, shortName: "노슬", countsTowardWeeklyLimit: true },
  { id: "lucid_easy", bossId: "lucid", koreanName: "이지 루시드", difficulty: "easy", cycle: "weekly", maxParty: 6, entryLevel: 220, released: true, nexonDifficulty: "easy", sortOrder: 410, shortName: "이루", countsTowardWeeklyLimit: true },
  { id: "will_easy", bossId: "will", koreanName: "이지 윌", difficulty: "easy", cycle: "weekly", maxParty: 6, entryLevel: 235, released: true, nexonDifficulty: "easy", sortOrder: 420, shortName: "이윌", countsTowardWeeklyLimit: true },
  { id: "lucid_normal", bossId: "lucid", koreanName: "노멀 루시드", difficulty: "normal", cycle: "weekly", maxParty: 6, entryLevel: 220, released: true, nexonDifficulty: "normal", sortOrder: 430, shortName: "노루", countsTowardWeeklyLimit: true },
  { id: "will_normal", bossId: "will", koreanName: "노멀 윌", difficulty: "normal", cycle: "weekly", maxParty: 6, entryLevel: 235, released: true, nexonDifficulty: "normal", sortOrder: 440, shortName: "노윌", countsTowardWeeklyLimit: true },
  { id: "dusk_normal", bossId: "dusk", koreanName: "노멀 더스크", difficulty: "normal", cycle: "weekly", maxParty: 6, entryLevel: 245, released: true, nexonDifficulty: "normal", sortOrder: 450, shortName: "노더", countsTowardWeeklyLimit: true },
  { id: "dunkel_normal", bossId: "dunkel", koreanName: "노멀 듄켈", difficulty: "normal", cycle: "weekly", maxParty: 6, entryLevel: 255, released: true, nexonDifficulty: "normal", sortOrder: 460, shortName: "노듄", countsTowardWeeklyLimit: true },
  { id: "damien_hard", bossId: "damien", koreanName: "하드 데미안", difficulty: "hard", cycle: "weekly", maxParty: 6, entryLevel: 190, released: true, nexonDifficulty: "hard", sortOrder: 470, shortName: "하데", countsTowardWeeklyLimit: true },
  { id: "lotus_hard", bossId: "lotus", koreanName: "하드 스우", difficulty: "hard", cycle: "weekly", maxParty: 6, entryLevel: 190, released: true, nexonDifficulty: "hard", sortOrder: 480, shortName: "하스", countsTowardWeeklyLimit: true },
  { id: "lucid_hard", bossId: "lucid", koreanName: "하드 루시드", difficulty: "hard", cycle: "weekly", maxParty: 6, entryLevel: 220, released: true, nexonDifficulty: "hard", sortOrder: 490, shortName: "하루", countsTowardWeeklyLimit: true },
  { id: "dusk_chaos", bossId: "dusk", koreanName: "카오스 더스크", difficulty: "chaos", cycle: "weekly", maxParty: 6, entryLevel: 245, released: true, nexonDifficulty: "chaos", sortOrder: 500, shortName: "카더", countsTowardWeeklyLimit: true },
  { id: "verus_hilla_normal", bossId: "verus_hilla", koreanName: "노멀 진 힐라", difficulty: "normal", cycle: "weekly", maxParty: 6, entryLevel: 250, released: true, nexonDifficulty: "normal", sortOrder: 510, shortName: "노진", countsTowardWeeklyLimit: true },
  { id: "guardian_angel_slime_chaos", bossId: "guardian_angel_slime", koreanName: "카오스 가디언 엔젤 슬라임", difficulty: "chaos", cycle: "weekly", maxParty: 6, entryLevel: 210, released: true, nexonDifficulty: "chaos", sortOrder: 520, shortName: "카슬", countsTowardWeeklyLimit: true },
  { id: "will_hard", bossId: "will", koreanName: "하드 윌", difficulty: "hard", cycle: "weekly", maxParty: 6, entryLevel: 235, released: true, nexonDifficulty: "hard", sortOrder: 530, shortName: "하윌", countsTowardWeeklyLimit: true },
  { id: "dunkel_hard", bossId: "dunkel", koreanName: "하드 듄켈", difficulty: "hard", cycle: "weekly", maxParty: 6, entryLevel: 255, released: true, nexonDifficulty: "hard", sortOrder: 540, shortName: "하듄", countsTowardWeeklyLimit: true },
  { id: "verus_hilla_hard", bossId: "verus_hilla", koreanName: "하드 진 힐라", difficulty: "hard", cycle: "weekly", maxParty: 6, entryLevel: 250, released: true, nexonDifficulty: "hard", sortOrder: 550, shortName: "하진", countsTowardWeeklyLimit: true },
  { id: "seren_normal", bossId: "seren", koreanName: "노멀 선택받은 세렌", difficulty: "normal", cycle: "weekly", maxParty: 6, entryLevel: 260, released: true, nexonDifficulty: "normal", sortOrder: 560, shortName: "노세", countsTowardWeeklyLimit: true },
  { id: "kalos_easy", bossId: "kalos", koreanName: "이지 감시자 칼로스", difficulty: "easy", cycle: "weekly", maxParty: 6, entryLevel: 265, released: true, nexonDifficulty: "easy", sortOrder: 570, shortName: "이칼", countsTowardWeeklyLimit: true },
  { id: "first_adversary_easy", bossId: "first_adversary", koreanName: "이지 최초의 대적자", difficulty: "easy", cycle: "weekly", maxParty: 3, entryLevel: 270, released: true, nexonDifficulty: "easy", sortOrder: 580, shortName: "이대", countsTowardWeeklyLimit: true },
  { id: "seren_hard", bossId: "seren", koreanName: "하드 선택받은 세렌", difficulty: "hard", cycle: "weekly", maxParty: 6, entryLevel: 260, released: true, nexonDifficulty: "hard", sortOrder: 590, shortName: "하세", countsTowardWeeklyLimit: true },
  { id: "kaling_easy", bossId: "kaling", koreanName: "이지 카링", difficulty: "easy", cycle: "weekly", maxParty: 6, entryLevel: 275, released: true, nexonDifficulty: "easy", sortOrder: 600, shortName: "이카", countsTowardWeeklyLimit: true },
  { id: "bellona_easy", bossId: "bellona", koreanName: "이지 벨로나", difficulty: "easy", cycle: "weekly", maxParty: 3, entryLevel: 280, released: true, nexonDifficulty: "easy", sortOrder: 610, shortName: "이벨", countsTowardWeeklyLimit: true },
  { id: "kalos_normal", bossId: "kalos", koreanName: "노멀 감시자 칼로스", difficulty: "normal", cycle: "weekly", maxParty: 6, entryLevel: 265, released: true, nexonDifficulty: "normal", sortOrder: 620, shortName: "노칼", countsTowardWeeklyLimit: true },
  { id: "first_adversary_normal", bossId: "first_adversary", koreanName: "노멀 최초의 대적자", difficulty: "normal", cycle: "weekly", maxParty: 3, entryLevel: 270, released: true, nexonDifficulty: "normal", sortOrder: 630, shortName: "노대", countsTowardWeeklyLimit: true },
  { id: "lotus_extreme", bossId: "lotus", koreanName: "익스트림 스우", difficulty: "extreme", cycle: "weekly", maxParty: 2, entryLevel: 190, released: true, nexonDifficulty: "extreme", sortOrder: 640, shortName: "익스", countsTowardWeeklyLimit: true },
  { id: "radiant_malefic_star_normal", bossId: "radiant_malefic_star", koreanName: "노멀 찬란한 흉성", difficulty: "normal", cycle: "weekly", maxParty: 3, entryLevel: 280, released: true, nexonDifficulty: "normal", sortOrder: 650, shortName: "노흉", countsTowardWeeklyLimit: true },
  { id: "kaling_normal", bossId: "kaling", koreanName: "노멀 카링", difficulty: "normal", cycle: "weekly", maxParty: 6, entryLevel: 275, released: true, nexonDifficulty: "normal", sortOrder: 660, shortName: "노카", countsTowardWeeklyLimit: true },
  { id: "bellona_normal", bossId: "bellona", koreanName: "노멀 벨로나", difficulty: "normal", cycle: "weekly", maxParty: 3, entryLevel: 280, released: true, nexonDifficulty: "normal", sortOrder: 670, shortName: "노벨", countsTowardWeeklyLimit: true },
  { id: "limbo_normal", bossId: "limbo", koreanName: "노멀 림보", difficulty: "normal", cycle: "weekly", maxParty: 3, entryLevel: 285, released: true, nexonDifficulty: "normal", sortOrder: 680, shortName: "노림", countsTowardWeeklyLimit: true },
  { id: "kalos_chaos", bossId: "kalos", koreanName: "카오스 감시자 칼로스", difficulty: "chaos", cycle: "weekly", maxParty: 6, entryLevel: 265, released: true, nexonDifficulty: "chaos", sortOrder: 690, shortName: "카칼", countsTowardWeeklyLimit: true },
  { id: "baldrix_normal", bossId: "baldrix", koreanName: "노멀 발드릭스", difficulty: "normal", cycle: "weekly", maxParty: 3, entryLevel: 290, released: true, nexonDifficulty: "normal", sortOrder: 700, shortName: "노발", countsTowardWeeklyLimit: true },
  { id: "first_adversary_hard", bossId: "first_adversary", koreanName: "하드 최초의 대적자", difficulty: "hard", cycle: "weekly", maxParty: 3, entryLevel: 270, released: true, nexonDifficulty: "hard", sortOrder: 710, shortName: "하대", countsTowardWeeklyLimit: true },
  { id: "jupiter_normal", bossId: "jupiter", koreanName: "노멀 유피테르", difficulty: "normal", cycle: "weekly", maxParty: 3, entryLevel: 295, released: true, nexonDifficulty: "normal", sortOrder: 720, shortName: "노유", countsTowardWeeklyLimit: true },
  { id: "kaling_hard", bossId: "kaling", koreanName: "하드 카링", difficulty: "hard", cycle: "weekly", maxParty: 6, entryLevel: 275, released: true, nexonDifficulty: "hard", sortOrder: 730, shortName: "하카", countsTowardWeeklyLimit: true },
  { id: "limbo_hard", bossId: "limbo", koreanName: "하드 림보", difficulty: "hard", cycle: "weekly", maxParty: 3, entryLevel: 285, released: true, nexonDifficulty: "hard", sortOrder: 740, shortName: "하림", countsTowardWeeklyLimit: true },
  { id: "radiant_malefic_star_hard", bossId: "radiant_malefic_star", koreanName: "하드 찬란한 흉성", difficulty: "hard", cycle: "weekly", maxParty: 3, entryLevel: 280, released: true, nexonDifficulty: "hard", sortOrder: 750, shortName: "하흉", countsTowardWeeklyLimit: true },
  { id: "seren_extreme", bossId: "seren", koreanName: "익스트림 선택받은 세렌", difficulty: "extreme", cycle: "weekly", maxParty: 6, entryLevel: 260, released: true, nexonDifficulty: "extreme", sortOrder: 760, shortName: "익세", countsTowardWeeklyLimit: true },
  { id: "bellona_hard", bossId: "bellona", koreanName: "하드 벨로나", difficulty: "hard", cycle: "weekly", maxParty: 3, entryLevel: 280, released: true, nexonDifficulty: "hard", sortOrder: 770, shortName: "하벨", countsTowardWeeklyLimit: true },
  { id: "baldrix_hard", bossId: "baldrix", koreanName: "하드 발드릭스", difficulty: "hard", cycle: "weekly", maxParty: 3, entryLevel: 290, released: true, nexonDifficulty: "hard", sortOrder: 780, shortName: "하발", countsTowardWeeklyLimit: true },
  { id: "kalos_extreme", bossId: "kalos", koreanName: "익스트림 감시자 칼로스", difficulty: "extreme", cycle: "weekly", maxParty: 6, entryLevel: 265, released: true, nexonDifficulty: "extreme", sortOrder: 790, shortName: "익칼", countsTowardWeeklyLimit: true },
  { id: "first_adversary_extreme", bossId: "first_adversary", koreanName: "익스트림 최초의 대적자", difficulty: "extreme", cycle: "weekly", maxParty: 3, entryLevel: 270, released: true, nexonDifficulty: "extreme", sortOrder: 800, shortName: "익대", countsTowardWeeklyLimit: true },
  { id: "jupiter_hard", bossId: "jupiter", koreanName: "하드 유피테르", difficulty: "hard", cycle: "weekly", maxParty: 3, entryLevel: 295, released: true, nexonDifficulty: "hard", sortOrder: 810, shortName: "하유", countsTowardWeeklyLimit: true },
  { id: "kaling_extreme", bossId: "kaling", koreanName: "익스트림 카링", difficulty: "extreme", cycle: "weekly", maxParty: 6, entryLevel: 275, released: true, nexonDifficulty: "extreme", sortOrder: 820, shortName: "익카", countsTowardWeeklyLimit: true },
  { id: "black_mage_hard", bossId: "black_mage", koreanName: "하드 검은 마법사", difficulty: "hard", cycle: "monthly", maxParty: 6, entryLevel: 255, released: true, nexonDifficulty: "hard", sortOrder: 910, shortName: "하검", countsTowardWeeklyLimit: true },
  { id: "black_mage_extreme", bossId: "black_mage", koreanName: "익스트림 검은 마법사", difficulty: "extreme", cycle: "monthly", maxParty: 6, entryLevel: 255, released: true, nexonDifficulty: "extreme", sortOrder: 920, shortName: "익검", countsTowardWeeklyLimit: true },
  { id: "meilin_normal", bossId: "meilin", koreanName: "노멀 메이린", difficulty: "normal", cycle: "weekly", maxParty: 3, entryLevel: 260, released: true, nexonDifficulty: "normal", sortOrder: 900, shortName: "노메", countsTowardWeeklyLimit: false },
  { id: "meilin_hard", bossId: "meilin", koreanName: "하드 메이린", difficulty: "hard", cycle: "weekly", maxParty: 3, entryLevel: 260, released: true, nexonDifficulty: "hard", sortOrder: 910, shortName: "하메", countsTowardWeeklyLimit: false },
];

/** 83건. 미확인(null) 3건 — §1.3 D4. */
export const GENERATED_BOSS_PRICES: readonly GeneratedBossPrice[] = [
  { bossDifficultyId: "zakum_easy", priceMeso: 114000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "zakum_normal", priceMeso: 349000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "papulatus_easy", priceMeso: 390000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "magnus_easy", priceMeso: 411000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "hilla_normal", priceMeso: 455000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "horntail_easy", priceMeso: 502000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "bloody_queen_normal", priceMeso: 551000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "von_bon_normal", priceMeso: 551000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "pierre_normal", priceMeso: 551000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "vellum_normal", priceMeso: 551000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "horntail_normal", priceMeso: 576000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "von_leon_easy", priceMeso: 602000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "arkarium_easy", priceMeso: 656000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "kaung_normal", priceMeso: 712000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "horntail_chaos", priceMeso: 770000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "pink_bean_normal", priceMeso: 799000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "von_leon_normal", priceMeso: 830000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "von_leon_hard", priceMeso: 1070000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "arkarium_normal", priceMeso: 1110000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "magnus_normal", priceMeso: 1160000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "papulatus_normal", priceMeso: 1200000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "hilla_hard", priceMeso: 1280000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "pink_bean_chaos", priceMeso: 1320000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "cygnus_normal", priceMeso: 1360000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "zakum_chaos", priceMeso: 8080000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "bloody_queen_chaos", priceMeso: 8140000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "von_bon_chaos", priceMeso: 8150000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "pierre_chaos", priceMeso: 8170000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "magnus_hard", priceMeso: 8560000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "vellum_chaos", priceMeso: 9280000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "papulatus_chaos", priceMeso: 13100000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "lotus_normal", priceMeso: 16700000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "damien_normal", priceMeso: 17500000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "guardian_angel_slime_normal", priceMeso: 25500000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "lucid_easy", priceMeso: 29800000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "will_easy", priceMeso: 32300000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "lucid_normal", priceMeso: 35600000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "will_normal", priceMeso: 41100000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "dusk_normal", priceMeso: 44000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "dunkel_normal", priceMeso: 47500000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "damien_hard", priceMeso: 48900000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "lotus_hard", priceMeso: 51500000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "lucid_hard", priceMeso: 62900000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "dusk_chaos", priceMeso: 69800000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "verus_hilla_normal", priceMeso: 71200000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "guardian_angel_slime_chaos", priceMeso: 75100000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "will_hard", priceMeso: 77100000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "dunkel_hard", priceMeso: 94400000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "verus_hilla_hard", priceMeso: 106000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "seren_normal", priceMeso: 239000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "kalos_easy", priceMeso: 280000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "first_adversary_easy", priceMeso: 308000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "seren_hard", priceMeso: 356000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "kaling_easy", priceMeso: 377000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "bellona_easy", priceMeso: null, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "kalos_normal", priceMeso: 505000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "first_adversary_normal", priceMeso: 560000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "lotus_extreme", priceMeso: 574000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "radiant_malefic_star_normal", priceMeso: 625000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "kaling_normal", priceMeso: 678000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "bellona_normal", priceMeso: null, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "limbo_normal", priceMeso: 1026000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "kalos_chaos", priceMeso: 1273000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "baldrix_normal", priceMeso: 1368000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "first_adversary_hard", priceMeso: 1435000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "jupiter_normal", priceMeso: 1615000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "kaling_hard", priceMeso: 1739000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "limbo_hard", priceMeso: 2385000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "radiant_malefic_star_hard", priceMeso: 2678000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "seren_extreme", priceMeso: 2835000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "bellona_hard", priceMeso: null, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "baldrix_hard", priceMeso: 3078000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "kalos_extreme", priceMeso: 4104000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "first_adversary_extreme", priceMeso: 4712000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "jupiter_hard", priceMeso: 4845000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "kaling_extreme", priceMeso: 5387000000, effectiveFrom: "2026-06-17T15:00:00.000Z", patchLabel: "1.2.202 (2026-06-18)" },
  { bossDifficultyId: "black_mage_hard", priceMeso: 665000000, effectiveFrom: "2026-06-30T15:00:00.000Z", patchLabel: "월간 결정 2026-07-01 적용" },
  { bossDifficultyId: "black_mage_extreme", priceMeso: 8740000000, effectiveFrom: "2026-06-30T15:00:00.000Z", patchLabel: "월간 결정 2026-07-01 적용" },
  { bossDifficultyId: "bellona_hard", priceMeso: 2950000000, effectiveFrom: "2026-08-19T15:00:00.000Z", patchLabel: "벨로나 출시 (2026-08-20)" },
  { bossDifficultyId: "bellona_normal", priceMeso: 850000000, effectiveFrom: "2026-08-19T15:00:00.000Z", patchLabel: "벨로나 출시 (2026-08-20)" },
  { bossDifficultyId: "bellona_easy", priceMeso: 440000000, effectiveFrom: "2026-08-19T15:00:00.000Z", patchLabel: "벨로나 출시 (2026-08-20)" },
  { bossDifficultyId: "meilin_normal", priceMeso: 300000000, effectiveFrom: "2026-08-24T15:00:00.000Z", patchLabel: "2026 OVERDRIVE" },
  { bossDifficultyId: "meilin_hard", priceMeso: 600000000, effectiveFrom: "2026-08-24T15:00:00.000Z", patchLabel: "2026 OVERDRIVE" },
];

/** 216건. */
export const GENERATED_BOSS_ALIASES: readonly GeneratedBossAlias[] = [
  { bossId: "zakum", bossDifficultyId: null, alias: "자쿰", normalizedAlias: "자쿰" },
  { bossId: "zakum", bossDifficultyId: null, alias: "쟈쿰", normalizedAlias: "쟈쿰" },
  { bossId: "papulatus", bossDifficultyId: null, alias: "파풀라투스", normalizedAlias: "파풀라투스" },
  { bossId: "papulatus", bossDifficultyId: null, alias: "파풀", normalizedAlias: "파풀" },
  { bossId: "magnus", bossDifficultyId: null, alias: "매그너스", normalizedAlias: "매그너스" },
  { bossId: "magnus", bossDifficultyId: null, alias: "매그", normalizedAlias: "매그" },
  { bossId: "hilla", bossDifficultyId: null, alias: "힐라", normalizedAlias: "힐라" },
  { bossId: "horntail", bossDifficultyId: null, alias: "혼테일", normalizedAlias: "혼테일" },
  { bossId: "horntail", bossDifficultyId: null, alias: "혼테", normalizedAlias: "혼테" },
  { bossId: "bloody_queen", bossDifficultyId: null, alias: "블러디퀸", normalizedAlias: "블러디퀸" },
  { bossId: "bloody_queen", bossDifficultyId: null, alias: "블퀸", normalizedAlias: "블퀸" },
  { bossId: "von_bon", bossDifficultyId: null, alias: "반반", normalizedAlias: "반반" },
  { bossId: "pierre", bossDifficultyId: null, alias: "피에르", normalizedAlias: "피에르" },
  { bossId: "von_leon", bossDifficultyId: null, alias: "반레온", normalizedAlias: "반레온" },
  { bossId: "von_leon", bossDifficultyId: null, alias: "반레", normalizedAlias: "반레" },
  { bossId: "arkarium", bossDifficultyId: null, alias: "아카이럼", normalizedAlias: "아카이럼" },
  { bossId: "arkarium", bossDifficultyId: null, alias: "아카", normalizedAlias: "아카" },
  { bossId: "kaung", bossDifficultyId: null, alias: "카웅", normalizedAlias: "카웅" },
  { bossId: "pink_bean", bossDifficultyId: null, alias: "핑크빈", normalizedAlias: "핑크빈" },
  { bossId: "pink_bean", bossDifficultyId: null, alias: "핑빈", normalizedAlias: "핑빈" },
  { bossId: "cygnus", bossDifficultyId: null, alias: "시그너스", normalizedAlias: "시그너스" },
  { bossId: "cygnus", bossDifficultyId: null, alias: "시그", normalizedAlias: "시그" },
  { bossId: "cygnus", bossDifficultyId: null, alias: "여제", normalizedAlias: "여제" },
  { bossId: "lotus", bossDifficultyId: null, alias: "스우", normalizedAlias: "스우" },
  { bossId: "damien", bossDifficultyId: null, alias: "데미안", normalizedAlias: "데미안" },
  { bossId: "damien", bossDifficultyId: null, alias: "데미", normalizedAlias: "데미" },
  { bossId: "guardian_angel_slime", bossDifficultyId: null, alias: "가엔슬", normalizedAlias: "가엔슬" },
  { bossId: "guardian_angel_slime", bossDifficultyId: null, alias: "슬라임", normalizedAlias: "슬라임" },
  { bossId: "guardian_angel_slime", bossDifficultyId: null, alias: "GAS", normalizedAlias: "gas" },
  { bossId: "lucid", bossDifficultyId: null, alias: "루시드", normalizedAlias: "루시드" },
  { bossId: "will", bossDifficultyId: null, alias: "윌", normalizedAlias: "윌" },
  { bossId: "dusk", bossDifficultyId: null, alias: "더스크", normalizedAlias: "더스크" },
  { bossId: "dunkel", bossDifficultyId: null, alias: "듄켈", normalizedAlias: "듄켈" },
  { bossId: "verus_hilla", bossDifficultyId: null, alias: "진힐라", normalizedAlias: "진힐라" },
  { bossId: "verus_hilla", bossDifficultyId: null, alias: "진힐", normalizedAlias: "진힐" },
  { bossId: "seren", bossDifficultyId: null, alias: "세렌", normalizedAlias: "세렌" },
  { bossId: "kalos", bossDifficultyId: null, alias: "칼로스", normalizedAlias: "칼로스" },
  { bossId: "first_adversary", bossDifficultyId: null, alias: "적자", normalizedAlias: "적자" },
  { bossId: "first_adversary", bossDifficultyId: null, alias: "최적자", normalizedAlias: "최적자" },
  { bossId: "kaling", bossDifficultyId: null, alias: "카링", normalizedAlias: "카링" },
  { bossId: "bellona", bossDifficultyId: null, alias: "벨로나", normalizedAlias: "벨로나" },
  { bossId: "radiant_malefic_star", bossDifficultyId: null, alias: "흉성", normalizedAlias: "흉성" },
  { bossId: "radiant_malefic_star", bossDifficultyId: null, alias: "찬흉", normalizedAlias: "찬흉" },
  { bossId: "limbo", bossDifficultyId: null, alias: "림보", normalizedAlias: "림보" },
  { bossId: "baldrix", bossDifficultyId: null, alias: "발드릭스", normalizedAlias: "발드릭스" },
  { bossId: "baldrix", bossDifficultyId: null, alias: "발드", normalizedAlias: "발드" },
  { bossId: "jupiter", bossDifficultyId: null, alias: "유피테르", normalizedAlias: "유피테르" },
  { bossId: "jupiter", bossDifficultyId: null, alias: "유피", normalizedAlias: "유피" },
  { bossId: "black_mage", bossDifficultyId: null, alias: "검마", normalizedAlias: "검마" },
  { bossId: "black_mage", bossDifficultyId: null, alias: "흑마", normalizedAlias: "흑마" },
  { bossId: "zakum", bossDifficultyId: "zakum_easy", alias: "이자쿰", normalizedAlias: "이자쿰" },
  { bossId: "zakum", bossDifficultyId: "zakum_easy", alias: "이쟈쿰", normalizedAlias: "이쟈쿰" },
  { bossId: "zakum", bossDifficultyId: "zakum_easy", alias: "이자", normalizedAlias: "이자" },
  { bossId: "zakum", bossDifficultyId: "zakum_normal", alias: "노자쿰", normalizedAlias: "노자쿰" },
  { bossId: "zakum", bossDifficultyId: "zakum_normal", alias: "노자", normalizedAlias: "노자" },
  { bossId: "zakum", bossDifficultyId: "zakum_chaos", alias: "카자쿰", normalizedAlias: "카자쿰" },
  { bossId: "zakum", bossDifficultyId: "zakum_chaos", alias: "카쿰", normalizedAlias: "카쿰" },
  { bossId: "zakum", bossDifficultyId: "zakum_chaos", alias: "카자", normalizedAlias: "카자" },
  { bossId: "papulatus", bossDifficultyId: "papulatus_easy", alias: "이파풀", normalizedAlias: "이파풀" },
  { bossId: "papulatus", bossDifficultyId: "papulatus_easy", alias: "이파", normalizedAlias: "이파" },
  { bossId: "papulatus", bossDifficultyId: "papulatus_normal", alias: "노파풀", normalizedAlias: "노파풀" },
  { bossId: "papulatus", bossDifficultyId: "papulatus_normal", alias: "노파", normalizedAlias: "노파" },
  { bossId: "papulatus", bossDifficultyId: "papulatus_chaos", alias: "카파풀", normalizedAlias: "카파풀" },
  { bossId: "papulatus", bossDifficultyId: "papulatus_chaos", alias: "카파", normalizedAlias: "카파" },
  { bossId: "magnus", bossDifficultyId: "magnus_easy", alias: "이매그", normalizedAlias: "이매그" },
  { bossId: "magnus", bossDifficultyId: "magnus_easy", alias: "이매", normalizedAlias: "이매" },
  { bossId: "magnus", bossDifficultyId: "magnus_normal", alias: "노매그", normalizedAlias: "노매그" },
  { bossId: "magnus", bossDifficultyId: "magnus_normal", alias: "노매", normalizedAlias: "노매" },
  { bossId: "magnus", bossDifficultyId: "magnus_hard", alias: "하매그", normalizedAlias: "하매그" },
  { bossId: "magnus", bossDifficultyId: "magnus_hard", alias: "하매", normalizedAlias: "하매" },
  { bossId: "hilla", bossDifficultyId: "hilla_normal", alias: "노힐라", normalizedAlias: "노힐라" },
  { bossId: "hilla", bossDifficultyId: "hilla_normal", alias: "노힐", normalizedAlias: "노힐" },
  { bossId: "hilla", bossDifficultyId: "hilla_hard", alias: "하드힐라", normalizedAlias: "하드힐라" },
  { bossId: "hilla", bossDifficultyId: "hilla_hard", alias: "하힐라", normalizedAlias: "하힐라" },
  { bossId: "hilla", bossDifficultyId: "hilla_hard", alias: "하힐", normalizedAlias: "하힐" },
  { bossId: "horntail", bossDifficultyId: "horntail_easy", alias: "이혼테", normalizedAlias: "이혼테" },
  { bossId: "horntail", bossDifficultyId: "horntail_easy", alias: "이혼", normalizedAlias: "이혼" },
  { bossId: "horntail", bossDifficultyId: "horntail_normal", alias: "노혼테", normalizedAlias: "노혼테" },
  { bossId: "horntail", bossDifficultyId: "horntail_normal", alias: "노혼", normalizedAlias: "노혼" },
  { bossId: "horntail", bossDifficultyId: "horntail_chaos", alias: "카혼테", normalizedAlias: "카혼테" },
  { bossId: "horntail", bossDifficultyId: "horntail_chaos", alias: "카혼", normalizedAlias: "카혼" },
  { bossId: "horntail", bossDifficultyId: "horntail_chaos", alias: "카오스혼테일", normalizedAlias: "카오스혼테일" },
  { bossId: "bloody_queen", bossDifficultyId: "bloody_queen_normal", alias: "노블퀸", normalizedAlias: "노블퀸" },
  { bossId: "bloody_queen", bossDifficultyId: "bloody_queen_normal", alias: "노블", normalizedAlias: "노블" },
  { bossId: "bloody_queen", bossDifficultyId: "bloody_queen_chaos", alias: "카블퀸", normalizedAlias: "카블퀸" },
  { bossId: "bloody_queen", bossDifficultyId: "bloody_queen_chaos", alias: "카블", normalizedAlias: "카블" },
  { bossId: "von_bon", bossDifficultyId: "von_bon_normal", alias: "노반반", normalizedAlias: "노반반" },
  { bossId: "von_bon", bossDifficultyId: "von_bon_chaos", alias: "카반반", normalizedAlias: "카반반" },
  { bossId: "von_bon", bossDifficultyId: "von_bon_chaos", alias: "카반", normalizedAlias: "카반" },
  { bossId: "pierre", bossDifficultyId: "pierre_normal", alias: "노피에르", normalizedAlias: "노피에르" },
  { bossId: "pierre", bossDifficultyId: "pierre_normal", alias: "노피", normalizedAlias: "노피" },
  { bossId: "pierre", bossDifficultyId: "pierre_chaos", alias: "카피에르", normalizedAlias: "카피에르" },
  { bossId: "pierre", bossDifficultyId: "pierre_chaos", alias: "카피", normalizedAlias: "카피" },
  { bossId: "von_leon", bossDifficultyId: "von_leon_easy", alias: "이반레", normalizedAlias: "이반레" },
  { bossId: "von_leon", bossDifficultyId: "von_leon_easy", alias: "이반", normalizedAlias: "이반" },
  { bossId: "von_leon", bossDifficultyId: "von_leon_normal", alias: "노반레", normalizedAlias: "노반레" },
  { bossId: "von_leon", bossDifficultyId: "von_leon_hard", alias: "하반레", normalizedAlias: "하반레" },
  { bossId: "von_leon", bossDifficultyId: "von_leon_hard", alias: "하반", normalizedAlias: "하반" },
  { bossId: "von_leon", bossDifficultyId: "von_leon_hard", alias: "하드반레온", normalizedAlias: "하드반레온" },
  { bossId: "arkarium", bossDifficultyId: "arkarium_easy", alias: "이아카", normalizedAlias: "이아카" },
  { bossId: "arkarium", bossDifficultyId: "arkarium_normal", alias: "노아카", normalizedAlias: "노아카" },
  { bossId: "kaung", bossDifficultyId: "kaung_normal", alias: "노카웅", normalizedAlias: "노카웅" },
  { bossId: "pink_bean", bossDifficultyId: "pink_bean_normal", alias: "노핑빈", normalizedAlias: "노핑빈" },
  { bossId: "pink_bean", bossDifficultyId: "pink_bean_normal", alias: "노핑", normalizedAlias: "노핑" },
  { bossId: "pink_bean", bossDifficultyId: "pink_bean_chaos", alias: "카핑빈", normalizedAlias: "카핑빈" },
  { bossId: "pink_bean", bossDifficultyId: "pink_bean_chaos", alias: "카핑", normalizedAlias: "카핑" },
  { bossId: "pink_bean", bossDifficultyId: "pink_bean_chaos", alias: "카오스핑크빈", normalizedAlias: "카오스핑크빈" },
  { bossId: "cygnus", bossDifficultyId: "cygnus_normal", alias: "노시그", normalizedAlias: "노시그" },
  { bossId: "lotus", bossDifficultyId: "lotus_normal", alias: "노스우", normalizedAlias: "노스우" },
  { bossId: "lotus", bossDifficultyId: "lotus_normal", alias: "노스", normalizedAlias: "노스" },
  { bossId: "lotus", bossDifficultyId: "lotus_hard", alias: "하스우", normalizedAlias: "하스우" },
  { bossId: "lotus", bossDifficultyId: "lotus_hard", alias: "하스", normalizedAlias: "하스" },
  { bossId: "lotus", bossDifficultyId: "lotus_extreme", alias: "익스우", normalizedAlias: "익스우" },
  { bossId: "lotus", bossDifficultyId: "lotus_extreme", alias: "익스스우", normalizedAlias: "익스스우" },
  { bossId: "lotus", bossDifficultyId: "lotus_extreme", alias: "익스", normalizedAlias: "익스" },
  { bossId: "damien", bossDifficultyId: "damien_normal", alias: "노데미", normalizedAlias: "노데미" },
  { bossId: "damien", bossDifficultyId: "damien_normal", alias: "노데", normalizedAlias: "노데" },
  { bossId: "damien", bossDifficultyId: "damien_hard", alias: "하데미", normalizedAlias: "하데미" },
  { bossId: "damien", bossDifficultyId: "damien_hard", alias: "하데", normalizedAlias: "하데" },
  { bossId: "guardian_angel_slime", bossDifficultyId: "guardian_angel_slime_normal", alias: "노가엔슬", normalizedAlias: "노가엔슬" },
  { bossId: "guardian_angel_slime", bossDifficultyId: "guardian_angel_slime_chaos", alias: "카가엔슬", normalizedAlias: "카가엔슬" },
  { bossId: "guardian_angel_slime", bossDifficultyId: "guardian_angel_slime_chaos", alias: "카슬라임", normalizedAlias: "카슬라임" },
  { bossId: "lucid", bossDifficultyId: "lucid_easy", alias: "이루시드", normalizedAlias: "이루시드" },
  { bossId: "lucid", bossDifficultyId: "lucid_easy", alias: "이루", normalizedAlias: "이루" },
  { bossId: "lucid", bossDifficultyId: "lucid_normal", alias: "노루시드", normalizedAlias: "노루시드" },
  { bossId: "lucid", bossDifficultyId: "lucid_normal", alias: "노루", normalizedAlias: "노루" },
  { bossId: "lucid", bossDifficultyId: "lucid_hard", alias: "하루시드", normalizedAlias: "하루시드" },
  { bossId: "lucid", bossDifficultyId: "lucid_hard", alias: "하루", normalizedAlias: "하루" },
  { bossId: "will", bossDifficultyId: "will_easy", alias: "이윌", normalizedAlias: "이윌" },
  { bossId: "will", bossDifficultyId: "will_normal", alias: "노윌", normalizedAlias: "노윌" },
  { bossId: "will", bossDifficultyId: "will_hard", alias: "하윌", normalizedAlias: "하윌" },
  { bossId: "dusk", bossDifficultyId: "dusk_normal", alias: "노더스크", normalizedAlias: "노더스크" },
  { bossId: "dusk", bossDifficultyId: "dusk_normal", alias: "노더", normalizedAlias: "노더" },
  { bossId: "dusk", bossDifficultyId: "dusk_chaos", alias: "카더스크", normalizedAlias: "카더스크" },
  { bossId: "dusk", bossDifficultyId: "dusk_chaos", alias: "카더", normalizedAlias: "카더" },
  { bossId: "dunkel", bossDifficultyId: "dunkel_normal", alias: "노듄켈", normalizedAlias: "노듄켈" },
  { bossId: "dunkel", bossDifficultyId: "dunkel_normal", alias: "노듄", normalizedAlias: "노듄" },
  { bossId: "dunkel", bossDifficultyId: "dunkel_hard", alias: "하듄켈", normalizedAlias: "하듄켈" },
  { bossId: "dunkel", bossDifficultyId: "dunkel_hard", alias: "하듄", normalizedAlias: "하듄" },
  { bossId: "verus_hilla", bossDifficultyId: "verus_hilla_normal", alias: "노진힐라", normalizedAlias: "노진힐라" },
  { bossId: "verus_hilla", bossDifficultyId: "verus_hilla_normal", alias: "노진힐", normalizedAlias: "노진힐" },
  { bossId: "verus_hilla", bossDifficultyId: "verus_hilla_hard", alias: "하진힐라", normalizedAlias: "하진힐라" },
  { bossId: "verus_hilla", bossDifficultyId: "verus_hilla_hard", alias: "하진힐", normalizedAlias: "하진힐" },
  { bossId: "seren", bossDifficultyId: "seren_normal", alias: "노세렌", normalizedAlias: "노세렌" },
  { bossId: "seren", bossDifficultyId: "seren_normal", alias: "노세", normalizedAlias: "노세" },
  { bossId: "seren", bossDifficultyId: "seren_hard", alias: "하세렌", normalizedAlias: "하세렌" },
  { bossId: "seren", bossDifficultyId: "seren_hard", alias: "하세", normalizedAlias: "하세" },
  { bossId: "seren", bossDifficultyId: "seren_extreme", alias: "익세렌", normalizedAlias: "익세렌" },
  { bossId: "seren", bossDifficultyId: "seren_extreme", alias: "익세", normalizedAlias: "익세" },
  { bossId: "kalos", bossDifficultyId: "kalos_easy", alias: "이칼로스", normalizedAlias: "이칼로스" },
  { bossId: "kalos", bossDifficultyId: "kalos_easy", alias: "이칼", normalizedAlias: "이칼" },
  { bossId: "kalos", bossDifficultyId: "kalos_normal", alias: "노칼로스", normalizedAlias: "노칼로스" },
  { bossId: "kalos", bossDifficultyId: "kalos_normal", alias: "노칼", normalizedAlias: "노칼" },
  { bossId: "kalos", bossDifficultyId: "kalos_chaos", alias: "카칼로스", normalizedAlias: "카칼로스" },
  { bossId: "kalos", bossDifficultyId: "kalos_chaos", alias: "카칼", normalizedAlias: "카칼" },
  { bossId: "kalos", bossDifficultyId: "kalos_extreme", alias: "익칼로스", normalizedAlias: "익칼로스" },
  { bossId: "kalos", bossDifficultyId: "kalos_extreme", alias: "익칼", normalizedAlias: "익칼" },
  { bossId: "first_adversary", bossDifficultyId: "first_adversary_easy", alias: "이적자", normalizedAlias: "이적자" },
  { bossId: "first_adversary", bossDifficultyId: "first_adversary_easy", alias: "이최적자", normalizedAlias: "이최적자" },
  { bossId: "first_adversary", bossDifficultyId: "first_adversary_normal", alias: "노적자", normalizedAlias: "노적자" },
  { bossId: "first_adversary", bossDifficultyId: "first_adversary_normal", alias: "노최적자", normalizedAlias: "노최적자" },
  { bossId: "first_adversary", bossDifficultyId: "first_adversary_hard", alias: "하적자", normalizedAlias: "하적자" },
  { bossId: "first_adversary", bossDifficultyId: "first_adversary_hard", alias: "하최적자", normalizedAlias: "하최적자" },
  { bossId: "first_adversary", bossDifficultyId: "first_adversary_extreme", alias: "익적자", normalizedAlias: "익적자" },
  { bossId: "first_adversary", bossDifficultyId: "first_adversary_extreme", alias: "익최적자", normalizedAlias: "익최적자" },
  { bossId: "kaling", bossDifficultyId: "kaling_easy", alias: "이카링", normalizedAlias: "이카링" },
  { bossId: "kaling", bossDifficultyId: "kaling_easy", alias: "이카", normalizedAlias: "이카" },
  { bossId: "kaling", bossDifficultyId: "kaling_normal", alias: "노카링", normalizedAlias: "노카링" },
  { bossId: "kaling", bossDifficultyId: "kaling_normal", alias: "노카", normalizedAlias: "노카" },
  { bossId: "kaling", bossDifficultyId: "kaling_hard", alias: "하카링", normalizedAlias: "하카링" },
  { bossId: "kaling", bossDifficultyId: "kaling_hard", alias: "하카", normalizedAlias: "하카" },
  { bossId: "kaling", bossDifficultyId: "kaling_extreme", alias: "익카링", normalizedAlias: "익카링" },
  { bossId: "kaling", bossDifficultyId: "kaling_extreme", alias: "익카", normalizedAlias: "익카" },
  { bossId: "bellona", bossDifficultyId: "bellona_easy", alias: "이벨로나", normalizedAlias: "이벨로나" },
  { bossId: "bellona", bossDifficultyId: "bellona_easy", alias: "이벨", normalizedAlias: "이벨" },
  { bossId: "bellona", bossDifficultyId: "bellona_normal", alias: "노벨로나", normalizedAlias: "노벨로나" },
  { bossId: "bellona", bossDifficultyId: "bellona_hard", alias: "하벨로나", normalizedAlias: "하벨로나" },
  { bossId: "bellona", bossDifficultyId: "bellona_hard", alias: "하벨", normalizedAlias: "하벨" },
  { bossId: "radiant_malefic_star", bossDifficultyId: "radiant_malefic_star_normal", alias: "노흉성", normalizedAlias: "노흉성" },
  { bossId: "radiant_malefic_star", bossDifficultyId: "radiant_malefic_star_hard", alias: "하흉성", normalizedAlias: "하흉성" },
  { bossId: "radiant_malefic_star", bossDifficultyId: "radiant_malefic_star_hard", alias: "하흉", normalizedAlias: "하흉" },
  { bossId: "limbo", bossDifficultyId: "limbo_normal", alias: "노림보", normalizedAlias: "노림보" },
  { bossId: "limbo", bossDifficultyId: "limbo_normal", alias: "노림", normalizedAlias: "노림" },
  { bossId: "limbo", bossDifficultyId: "limbo_hard", alias: "하림보", normalizedAlias: "하림보" },
  { bossId: "limbo", bossDifficultyId: "limbo_hard", alias: "하림", normalizedAlias: "하림" },
  { bossId: "baldrix", bossDifficultyId: "baldrix_normal", alias: "노발드", normalizedAlias: "노발드" },
  { bossId: "baldrix", bossDifficultyId: "baldrix_hard", alias: "하발드릭스", normalizedAlias: "하발드릭스" },
  { bossId: "baldrix", bossDifficultyId: "baldrix_hard", alias: "하발드", normalizedAlias: "하발드" },
  { bossId: "jupiter", bossDifficultyId: "jupiter_normal", alias: "노유피", normalizedAlias: "노유피" },
  { bossId: "jupiter", bossDifficultyId: "jupiter_hard", alias: "하유피테르", normalizedAlias: "하유피테르" },
  { bossId: "jupiter", bossDifficultyId: "jupiter_hard", alias: "하유피", normalizedAlias: "하유피" },
  { bossId: "black_mage", bossDifficultyId: "black_mage_hard", alias: "하검마", normalizedAlias: "하검마" },
  { bossId: "black_mage", bossDifficultyId: "black_mage_hard", alias: "하검", normalizedAlias: "하검" },
  { bossId: "black_mage", bossDifficultyId: "black_mage_hard", alias: "하드검은마법사", normalizedAlias: "하드검은마법사" },
  { bossId: "black_mage", bossDifficultyId: "black_mage_extreme", alias: "익검마", normalizedAlias: "익검마" },
  { bossId: "black_mage", bossDifficultyId: "black_mage_extreme", alias: "익검", normalizedAlias: "익검" },
  { bossId: "black_mage", bossDifficultyId: "black_mage_extreme", alias: "익스검마", normalizedAlias: "익스검마" },
  { bossId: "first_adversary", bossDifficultyId: null, alias: "쌀", normalizedAlias: "쌀" },
  { bossId: "first_adversary", bossDifficultyId: "first_adversary_easy", alias: "이대", normalizedAlias: "이대" },
  { bossId: "first_adversary", bossDifficultyId: "first_adversary_normal", alias: "노대", normalizedAlias: "노대" },
  { bossId: "first_adversary", bossDifficultyId: "first_adversary_hard", alias: "하대", normalizedAlias: "하대" },
  { bossId: "first_adversary", bossDifficultyId: "first_adversary_extreme", alias: "익대", normalizedAlias: "익대" },
  { bossId: "first_adversary", bossDifficultyId: "first_adversary_easy", alias: "이쌀", normalizedAlias: "이쌀" },
  { bossId: "first_adversary", bossDifficultyId: "first_adversary_normal", alias: "노쌀", normalizedAlias: "노쌀" },
  { bossId: "first_adversary", bossDifficultyId: "first_adversary_hard", alias: "하쌀", normalizedAlias: "하쌀" },
  { bossId: "first_adversary", bossDifficultyId: "first_adversary_extreme", alias: "익쌀", normalizedAlias: "익쌀" },
  { bossId: "bellona", bossDifficultyId: "bellona_normal", alias: "노벨", normalizedAlias: "노벨" },
  { bossId: "meilin", bossDifficultyId: null, alias: "메이린", normalizedAlias: "메이린" },
  { bossId: "meilin", bossDifficultyId: null, alias: "메린", normalizedAlias: "메린" },
  { bossId: "meilin", bossDifficultyId: "meilin_normal", alias: "노메린", normalizedAlias: "노메린" },
  { bossId: "meilin", bossDifficultyId: "meilin_hard", alias: "하메린", normalizedAlias: "하메린" },
  { bossId: "kaung", bossDifficultyId: "kaung_normal", alias: "노웅", normalizedAlias: "노웅" },
  { bossId: "verus_hilla", bossDifficultyId: "verus_hilla_normal", alias: "노진", normalizedAlias: "노진" },
  { bossId: "verus_hilla", bossDifficultyId: "verus_hilla_hard", alias: "하진", normalizedAlias: "하진" },
  { bossId: "meilin", bossDifficultyId: "meilin_normal", alias: "노메", normalizedAlias: "노메" },
  { bossId: "meilin", bossDifficultyId: "meilin_hard", alias: "하메", normalizedAlias: "하메" },
];
